baseURL = "https://mailchain.github.io/"
languageCode = "en-us"
title = "Mailchain"
copyright = "Made with ❤️ by Mailchain contributors."
theme = "hugo-apex-theme"
pygmentsCodeFences = true
pygmentsStyle = "dracula"

[params]
logo = "https://mailchain.xyz/inbox/favicon.ico"