baseURL = "https://docs.mailchain.xyz/"
languageCode = "en-us"
title = "Mailchain"
copyright = "Made with ❤️ by Mailchain contributors."
theme = "hugo-apex-theme"
pygmentsCodeFences = true
pygmentsStyle = "dracula"

[params]
logo = "https://mailchain.xyz/images/app-logo-512.png"
ghdocsrepo = "https://github.com/mailchain/docs.mailchain.xyz/tree/master"